# Generated by Django 6.0.6 on 2026-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('submitted', 'Eingereicht'), ('reimbursed', 'Erstattet')], default='pending', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erstattet am')),
                ('ai_confidence', models.JSONField(blank=True, default=dict, verbose_name='KI-Konfidenz')),
                ('ai_raw_text', models.TextField(blank=True, verbose_name='KI-Rohtext')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Auslage',
                'verbose_name_plural': 'Auslagen',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('expense_purpose', models.CharField(default='Tanken Fahrzeug M-XO 475', max_length=255, verbose_name='Grund und Zweck')),
                ('place', models.CharField(default='Landshut', max_length=100, verbose_name='Ort')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Empfänger E-Mail')),
            ],
            options={
                'verbose_name': 'Auslagen-Konfiguration',
                'verbose_name_plural': 'Auslagen-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='ReimbursementSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/reimbursements/submissions/', verbose_name='PDF')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtbetrag')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingereicht am')),
                ('claims', models.ManyToManyField(related_name='submissions', to='reimbursements.expenseclaim', verbose_name='Belege')),
            ],
            options={
                'verbose_name': 'Einreichung',
                'verbose_name_plural': 'Einreichungen',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
