# Generated by Django 6.0.6 on 2026-06-06 08:04

import reimbursements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementconfig',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo für den Antrag (PNG, JPG, SVG, WEBP).', null=True, upload_to=reimbursements.models.config_logo_upload_path, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='reimbursementconfig',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Digitale Unterschrift als Bild (PNG, JPG, WEBP).', null=True, upload_to=reimbursements.models.config_signature_upload_path, verbose_name='Unterschrift'),
        ),
    ]
