# Generated by Django 6.0.7 on 2026-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('kind', models.CharField(choices=[('projekt', 'Projekt'), ('kunde', 'Kunde'), ('kostenstelle', 'Kostenstelle'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20, verbose_name='Dimension')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Farbe (Hex)')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='unique_tag_kind_name')],
            },
        ),
    ]
