# Generated by Django 4.2.30 on 2026-05-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_due', models.IntegerField(default=3, verbose_name='Tage vor Fälligkeit')),
                ('liquidity_threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liquiditätsschwelle (EUR)')),
                ('alert_due_enabled', models.BooleanField(default=True, verbose_name='Fälligkeits-Alerts aktiv')),
                ('alert_overdue_enabled', models.BooleanField(default=True, verbose_name='Überschreitungs-Alerts aktiv')),
                ('alert_liquidity_enabled', models.BooleanField(default=True, verbose_name='Liquiditäts-Alerts aktiv')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, max_length=255, verbose_name='SMTP Benutzer')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Passwort')),
                ('smtp_from', models.EmailField(blank=True, max_length=254, verbose_name='Absenderadresse')),
                ('smtp_tls', models.BooleanField(default=True, verbose_name='TLS verwenden')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Empfänger-Adresse')),
            ],
            options={
                'verbose_name': 'Alert-Konfiguration',
                'verbose_name_plural': 'Alert-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('due_soon', 'Fällig in Kürze'), ('overdue', 'Überfällig'), ('liquidity', 'Liquiditätsengpass')], max_length=20, verbose_name='Alert-Typ')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='Mail versendet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('dedup_key', models.CharField(max_length=255, unique=True, verbose_name='Dedup-Schlüssel')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bookings.booking', verbose_name='Buchung')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
