# Generated by Django 4.2.30 on 2026-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_dedup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfig',
            name='liquidity_threshold',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Liquiditätsschwelle (EUR)'),
        ),
    ]
