# Generated by Django 6.0.5 on 2026-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='anthropic', max_length=20, verbose_name='KI-Provider')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, verbose_name='OpenAI API Key')),
                ('openai_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='OpenAI Model')),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, verbose_name='Anthropic API Key')),
                ('anthropic_model', models.CharField(default='claude-3-5-haiku-20241022', max_length=100, verbose_name='Anthropic Model')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Max Tokens')),
                ('enabled', models.BooleanField(default=True, verbose_name='KI-Service aktiviert')),
            ],
            options={
                'verbose_name': 'KI-Konfiguration',
                'verbose_name_plural': 'KI-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='Provider')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('feature', models.CharField(max_length=50, verbose_name='Feature')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('success', models.BooleanField(verbose_name='Erfolgreich')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Dauer (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'KI-Anfrage Log',
                'verbose_name_plural': 'KI-Anfrage Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
