# Generated by Django 6.0.5 on 2026-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_booking_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringseries',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('semi_annual', 'Halbjährlich'), ('yearly', 'Jährlich')], max_length=20, verbose_name='Intervall'),
        ),
    ]
