# Generated by Django 6.0.5 on 2026-05-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_semi_annual_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('initial_amount', models.DecimalField(decimal_places=2, help_text='Aktueller Schuldenstand bei Erfassung', max_digits=10, verbose_name='Vortrag (€)')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='bookings.category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Verbindlichkeit',
                'verbose_name_plural': 'Verbindlichkeiten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='liability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.liability', verbose_name='Verbindlichkeit'),
        ),
    ]
