# Generated by Django 6.0.5 on 2026-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_liability_and_booking_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('real_estate', 'Immobilien'), ('vehicle', 'Fahrzeuge'), ('electronics', 'Elektronik'), ('investments', 'Wertpapiere & Investments'), ('bank_account', 'Bankguthaben & Sparkonten'), ('insurance', 'Versicherungen & Vorsorge'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kategorie')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Ursprünglicher Kaufpreis für Wertentwicklung', max_digits=12, null=True, verbose_name='Kaufpreis (€)')),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Geschätzter aktueller Marktwert', max_digits=12, verbose_name='Aktueller Wert (€)')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Vermögensgegenstand',
                'verbose_name_plural': 'Vermögensgegenstände',
                'ordering': ['-current_value'],
            },
        ),
    ]
