# Generated by Django 6.0.6 on 2026-06-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Ausgabe'), ('income', 'Einnahme'), ('neutral', 'Neutral')], default='expense', max_length=10, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Kurze Erklärung für den KI-Finanzassistenten', max_length=500, verbose_name='Beschreibung'),
        ),
    ]
