# Generated by Django 6.0.7 on 2026-07-24 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_populate_category_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ist-Gesamtstand')),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MoneyPlan-Soll')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Differenz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='bookings.booking', verbose_name='Ausgleichsbuchung')),
            ],
            options={
                'verbose_name': 'Abgleich-Protokoll',
                'verbose_name_plural': 'Abgleich-Protokolle',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
