# Generated by Django 6.0.7 on 2026-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_reconciliation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringseries',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
    ]
