# Generated by Django 6.0.7 on 2026-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_recurringseries_archived'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='tags.tag', verbose_name='Tags'),
        ),
    ]
