# Generated by Django 6.0.7 on 2026-08-19 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('account_type', models.CharField(choices=[('giro', 'Girokonto'), ('savings', 'Tagesgeld/Sparkonto'), ('cash', 'Bargeld'), ('credit_card', 'Kreditkarte'), ('paypal', 'PayPal'), ('other', 'Sonstiges')], default='giro', max_length=20, verbose_name='Typ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Konten',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kontostand (€)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='bookings.account', verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Kontostand',
                'verbose_name_plural': 'Kontostände',
                'ordering': ['-date', 'account__sort_order', 'account__name'],
                'constraints': [models.UniqueConstraint(fields=('account', 'date'), name='unique_account_balance_per_day')],
            },
        ),
    ]
