# Generated by Django 6.0.5 on 2026-05-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('duration', models.DecimalField(decimal_places=2, help_text='Stunden als Dezimalzahl: 1.5 = 1h 30min, 0.5 = 30min', max_digits=5, verbose_name='Dauer (h)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stundensatz')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('billed', models.BooleanField(default=False, verbose_name='Abgerechnet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timetracking.client', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
