# Generated by Django 6.0.7 on 2026-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('timetracking', '0001_initial_timetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='time_entries', to='tags.tag', verbose_name='Tags'),
        ),
    ]
